# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_measurement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 70, 111, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.comlabel.setObjectName("comlabel")
        self.verticalLayout.addWidget(self.comlabel)
        self.comBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comBox.setObjectName("comBox")
        self.verticalLayout.addWidget(self.comBox)
        self.BaudRatelabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.BaudRatelabel.setObjectName("BaudRatelabel")
        self.verticalLayout.addWidget(self.BaudRatelabel)
        self.BaudRateBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.BaudRateBox.setObjectName("BaudRateBox")
        self.BaudRateBox.addItem("")
        self.BaudRateBox.setItemText(0, "")
        self.BaudRateBox.addItem("")
        self.verticalLayout.addWidget(self.BaudRateBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 230, 111, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.openButton.setObjectName("openButton")
        self.verticalLayout_2.addWidget(self.openButton)
        self.closeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        self.LineDisplayBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LineDisplayBox.setGeometry(QtCore.QRect(10, 60, 601, 281))
        self.LineDisplayBox.setObjectName("LineDisplayBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comlabel.setText(_translate("MainWindow", "com:"))
        self.BaudRatelabel.setText(_translate("MainWindow", "Baud Rate:"))
        self.BaudRateBox.setItemText(1, _translate("MainWindow", "115200"))
        self.openButton.setText(_translate("MainWindow", "open"))
        self.closeButton.setText(_translate("MainWindow", "close"))
        self.LineDisplayBox.setTitle(_translate("MainWindow", "Line Display"))
